import{S as m,i as n}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function f(s){return s.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:t,comments:a,downloads:u})=>`
        <div class="foto-card">
            <a class="gallery-link" href="${o}">
                <img class="gallery-img" src="${r}" alt="${i}" />
                <ul class="search-list">
                    <li><span class="info-item">Likes</span>${e}</li>
                    <li><span class="info-item">Views</span>${t}</li>
                    <li><span class="info-item">Comments</span>${a}</li>
                    <li><span class="info-item">Downloads</span>${u}</li>
                </ul>
            </a>
        </div>`).join("")}function d(s){const r="43290538-553335dd3499f06be9a5135a9",o=new URLSearchParams({key:r,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api?${o}`).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})}const h=document.querySelector("#search-form"),l=document.querySelector(".gallery"),c=document.querySelector(".loader"),p=new m(".gallery a",{captionsData:"alt",captionDelay:250});h.addEventListener("submit",g);function g(s){s.preventDefault(),l.innerHTML="";const r=s.currentTarget.elements.searchQuery.value.trim();if(!r){n.show({title:"error",titleColor:"white",message:"Please, enter a word ",messageColor:"white",color:"red",position:"topCenter",timeout:"2000"});return}c.classList.toggle("is-hidden"),d(r).then(o=>{if(o.total===0){n.show({title:"error",titleColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",color:"red",position:"topCenter",timeout:"2000"});return}l.insertAdjacentHTML("beforeend",f(o.hits)),p.refresh(),s.currentTarget.reset()}).catch(o=>{n.show({message:o.message})}).finally(()=>{c.classList.toggle("is-hidden")})}
//# sourceMappingURL=commonHelpers.js.map
